version: '3.3'

services:
  postgres:
    image: postgres:latest
    container_name: my_postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: my_database_name
    ports:
      - "5432:5432"
